-- ─────────────────────────────────────────────────────────────────────────
-- OmniWatch user_config.lua (auto-generated by //ow config)
-- ─────────────────────────────────────────────────────────────────────────
-- Hand-edit if you prefer. After changes, //lua r omniwatch.
-- ─────────────────────────────────────────────────────────────────────────
return {
    -- BLU gains Dual Wield from points spent in equipped Set 1/2
        -- spells: 4pts=8% DW, 8pts=15% DW, 12pts=25% DW, 18pts=30% DW.
        -- We can't easily read your spell sets from windower.ffxi.get_player(),
        -- so set this manually to match your typical melee BLU set. Set to 0
        -- when not playing BLU. Only applied when main_job == BLU.
    blu_dw_override = 0,

}
